web:
  build: .
  command: 'bash -c ''npm start'''
  working_dir: /app/user
  environment:
    PORT: 8081
    MONGOLAB_URI: 'mongolab:27017'
  ports:
    - '8081:8081'
  links:
    - mongolab
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8081
    MONGOLAB_URI: 'mongolab:27017'
  ports:
    - '8081:8081'
  links:
    - mongolab
  volumes:
    - '.:/app/user'
mongolab:
  image: mongo
